#! /usr/bin/env bash
while getopts :u:p:ab option; do
    case $option in
        u) user=$OPTARG;;
        p) pass=$OPTARG;;
        a) echo "Got the 'a' flag";;
        b) echo "Got the 'b' flag";;
        ?) echo "not matching the $OPTARG"
    esac
done

echo "user: $user / pass: $pass"